defaults: &defaults
  app_name: "YMCK Color | To be best printing supplier"
  domain: "http://www.ymckcolor.com"    
  facebook_app_id: 
  facebook_secret: 
  admin_emails: "xuhongwei420@gmail.com"
  google_analytics_key: "UA-54148940-1"
  default_logo_url: "/logo.png"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
